-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Wersja serwera:               10.11.0-MariaDB - mariadb.org binary distribution
-- Serwer OS:                    Win64
-- HeidiSQL Wersja:              11.3.0.6295
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Zrzut struktury tabela bookstore.klienci
CREATE TABLE IF NOT EXISTS `klienci` (
  `id_klienta` int(11) NOT NULL AUTO_INCREMENT,
  `login` varchar(20) COLLATE utf8mb4_polish_ci NOT NULL,
  `imie` varchar(30) COLLATE utf8mb4_polish_ci DEFAULT NULL,
  `nazwisko` varchar(30) COLLATE utf8mb4_polish_ci DEFAULT NULL,
  `miejscowosc` varchar(20) COLLATE utf8mb4_polish_ci DEFAULT NULL,
  `kod_pocztowy` varchar(6) COLLATE utf8mb4_polish_ci DEFAULT NULL,
  `ulica` varchar(20) COLLATE utf8mb4_polish_ci DEFAULT NULL,
  `nr_domu` varchar(4) COLLATE utf8mb4_polish_ci DEFAULT NULL,
  `nr_telefonu` varchar(11) COLLATE utf8mb4_polish_ci DEFAULT NULL,
  PRIMARY KEY (`id_klienta`),
  KEY `login` (`login`),
  CONSTRAINT `klienci_ibfk_1` FOREIGN KEY (`login`) REFERENCES `users` (`login`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_polish_ci;

-- Zrzucanie danych dla tabeli bookstore.klienci: ~0 rows (około)
/*!40000 ALTER TABLE `klienci` DISABLE KEYS */;
INSERT INTO `klienci` (`id_klienta`, `login`, `imie`, `nazwisko`, `miejscowosc`, `kod_pocztowy`, `ulica`, `nr_domu`, `nr_telefonu`) VALUES
	(3, 'admin', 'admin', 'admin1', 'admin1', 'admin2', 'admin3', NULL, 'admin');
/*!40000 ALTER TABLE `klienci` ENABLE KEYS */;

-- Zrzut struktury tabela bookstore.kody_rabatowe
CREATE TABLE IF NOT EXISTS `kody_rabatowe` (
  `id_rabatu` int(11) NOT NULL AUTO_INCREMENT,
  `kod` varchar(30) COLLATE utf8mb4_polish_ci DEFAULT NULL,
  `wartosc_rabatu` varchar(5) COLLATE utf8mb4_polish_ci DEFAULT NULL,
  `ilosc_kodow` int(5) DEFAULT 0,
  `data_wygasniecia` date DEFAULT NULL,
  PRIMARY KEY (`id_rabatu`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_polish_ci;

-- Zrzucanie danych dla tabeli bookstore.kody_rabatowe: ~0 rows (około)
/*!40000 ALTER TABLE `kody_rabatowe` DISABLE KEYS */;
/*!40000 ALTER TABLE `kody_rabatowe` ENABLE KEYS */;

-- Zrzut struktury tabela bookstore.koszyk
CREATE TABLE IF NOT EXISTS `koszyk` (
  `id_koszyka` int(11) NOT NULL AUTO_INCREMENT,
  `id_klienta` int(11) DEFAULT NULL,
  `id_product` int(11) DEFAULT NULL,
  `ilosc` int(11) DEFAULT NULL,
  PRIMARY KEY (`id_koszyka`),
  KEY `id_klienta` (`id_klienta`),
  KEY `id_product` (`id_product`),
  CONSTRAINT `FK_koszyk_klienci` FOREIGN KEY (`id_klienta`) REFERENCES `klienci` (`id_klienta`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_koszyk_ksiazki` FOREIGN KEY (`id_product`) REFERENCES `ksiazki` (`id_ksiazki`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_polish_ci;

-- Zrzucanie danych dla tabeli bookstore.koszyk: ~0 rows (około)
/*!40000 ALTER TABLE `koszyk` DISABLE KEYS */;
/*!40000 ALTER TABLE `koszyk` ENABLE KEYS */;

-- Zrzut struktury tabela bookstore.ksiazki
CREATE TABLE IF NOT EXISTS `ksiazki` (
  `id_ksiazki` int(11) NOT NULL AUTO_INCREMENT,
  `tytul` varchar(100) COLLATE utf8mb4_polish_ci DEFAULT NULL,
  `cena` float unsigned DEFAULT NULL,
  `ilosc_sztuk` int(5) DEFAULT 0,
  `ilosc_stron` int(5) DEFAULT 0,
  `data_wydania` varchar(10) COLLATE utf8mb4_polish_ci DEFAULT NULL,
  `opis` varchar(5000) COLLATE utf8mb4_polish_ci DEFAULT NULL,
  `autor` varchar(1000) COLLATE utf8mb4_polish_ci DEFAULT NULL,
  `okladka` text COLLATE utf8mb4_polish_ci DEFAULT NULL,
  `gatunek` varchar(50) COLLATE utf8mb4_polish_ci DEFAULT '0',
  PRIMARY KEY (`id_ksiazki`)
) ENGINE=InnoDB AUTO_INCREMENT=43 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_polish_ci;

-- Zrzucanie danych dla tabeli bookstore.ksiazki: ~24 rows (około)
/*!40000 ALTER TABLE `ksiazki` DISABLE KEYS */;
INSERT INTO `ksiazki` (`id_ksiazki`, `tytul`, `cena`, `ilosc_sztuk`, `ilosc_stron`, `data_wydania`, `opis`, `autor`, `okladka`, `gatunek`) VALUES
	(16, 'Harry Potter i kamień filozoficzny', 27.99, 30, 352, '2015-08-09', 'Harry Potter, sierota i podrzutek, od niemowlęcia wychowywany był przez ciotkę i wuja, którzy traktowali go jak piąte koło u wozu. Pochodzenie chłopca owiane jest tajemnicą; jedyną pamiątką Harry`ego z przeszłości jest zagadkowa blizna na czole. Skąd jednak biorą się niesamowite zjawiska, które towarzyszą nieświadomemu niczego Potterowi? Wszystko zmienia się w dniu jedenastych urodzin chłopca, kiedy dowiaduje się o istnieniu świata, o którym nie miał dotąd pojęcia.\r\nNowe wydanie książki o najsłynniejszym czarodzieju świata różni się od poprzednich nie tylko okładką, ale i wnętrzem – po raz pierwszy na początku każdego tomu pojawi się mapka Hogwartu i okolic, początki rozdziałów ozdobione będą specjalnymi gwiazdkami, a na końcu pierwszego tomu na Czytelników czeka coś zupełnie wyjątkowego – akt personalny J.K. Rowling, z którego można dowiedzieć się, jakie jest ulubione zwierzę czy bohater literacki autorki.', 'J.K. Rowling', 'upload/1669814997086494238-352x500.jpg', 'Fantastyka'),
	(17, 'Bractwo pierścienia. Władca Pierścieni.', 45.67, 49, 608, '2016-09-11', 'Pierwsza część słynnego cyklu Tolkiena "Władca Pierścieni". Osadzona, jak i pozostałe, w niezwykle oryginalnym świecie, utworzonym dzięki bogactwu i sile wyobraźni autora. Świat tej powieści wciąga i fascynuje, urzeka fikcyjną rzeczywistością, ze stworzoną na jej użytek geografią, historią, kulturą i mitologią.', 'J.R.R. Tolkien', 'upload/1669815244198973981-352x500.jpg', 'Fantastyka'),
	(18, 'Morderstwo w Orient Expressie', 52.38, 90, 272, '', 'Ekskluzywna edycja kolekcjonerska wybranych dzieł Agaty Christie z okazji 100-lecia wydania pierwszej książki z Herkulesem Poirot.\r\nHerkules Poirot po rozwiązaniu sprawy kryminalnej w Azji wraca do Europy. Pociąg Orient Express, którym podróżuje, grzęźnie w zaspie śnieżnej. W nocy w niewyjaśnionych okolicznościach ginie jeden z pasażerów. Detektyw Poirot rozpoczyna dochodzenie, a jego podróż zamienia się w śledztwo. Fakty wskazują, że zabójca zajmuje przedział w tym samym wagonie… Czy Poirot zdoła rozwiązać zagadkę tajemniczego morderstwa? Sprawa nie należy do łatwych - każdy pasażer jest podejrzany…', 'Agatha Christie', 'upload/1669815365701984743-352x500.jpg', 'Kryminał'),
	(19, 'Małe kobietki', 37.89, 69, 192, '', 'Ekskluzywna edycja oprawiona w delikatną gładką tkaninę o właściwościach jedwabiu.\r\nSiostry March, bohaterki najpopularniejszej powieści Louisy May Alcott rozkochały w sobie już wiele pokoleń czytelników. W „Małych kobietkach” czytelnik znajdzie ciepłe, lecz niepozbawione refleksji portrety czterech sióstr: utalentowanej chłopczycy i przyszłej pisarki Jo, wątłej i nieśmiałej Beth o złotym sercu, pięknej i ambitnej Meg oraz romantycznej, ale rozpieszczonej Amy. O jedność i byt rodziny dzielnie walczy ich matka Marmee, podczas gdy ojciec bierze udział w wojnie secesyjnej.\r\nNie jest tajemnicą, że Alcott napisała powieść, czerpiąc z własnych doświadczeń. Kiedy jej ojciec, wolnomyślicielski reformator i abolicjonista Bronson Alcott, prowadził dysputy z takimi znakomitościami jak Emerson, Thoreau i Hawthorne, Louisa utrzymywała siebie i siostry z drobnych prac, takich jak szycie, robienie prania czy praca w charakterze pomocy domowej.\r\nWkrótce jednak odkryła, że może więcej zarobić na pisaniu. „Małe kobietki” przyniosły jej nie tylko majątek, ale i sławę, choć daleko im do „książki dla dziewczynek”, o co prosił ją pierwszy wydawca. Powieść porusza tak ponadczasowe tematy, jak miłość i śmierć, wojna i pokój, konflikty między osobistymi ambicjami, a obowiązkami rodzinnymi czy zderzenie kultur dwóch kontynentów „starej” Europy i „nowej” Ameryki.', 'Louisa May Alcott', 'upload/1669815533057939478-352x500.jpg', 'Romans'),
	(20, 'Pamiętnik', 34.45, 78, 256, '2010-11-02', 'Karty starego notatnika kryją historię romantycznej miłości. Starszy pan codziennie odczytuje ją mieszkającej w domu opieki kobiecie chorej na alzheimera. Jest to opowieść o bogatej dziewczynie z miasta i ubogim chłopaku z prowincji, których pewnego lata połączyło wyjątkowe uczucie. Wbrew sobie zostali rozdzieleni, a ich miłość wystawiona na próbę. Czy uda im się ponownie spotkać?', 'Nicholas Sparks', '../../upload/test.png', 'Romans'),
	(21, 'Harry Potter i Komnata Tajemnic', 20.22, 87, 368, '2015-08-10', 'Harry po pełnym przygód roku w Hogwarcie spędza nudne wakacje u Dursleyów i z utęsknieniem wyczekuje powrotu do szkoły. Sprawy jednak znacznie się komplikują, gdy pewnego dnia odwiedza go tajemniczy przybysz i ostrzega przed… powrotem do Szkoły Magii i Czarodziejstwa, gdzie ma dojść do strasznych wydarzeń. Czy Harry posłucha ostrzeżenia? Co złego ma się wydarzyć w Hogwarcie? Jakie tajemnice skrywa rodzina Malfoya? I najważniejsze – czym jest i gdzie znajduje się tytułowa Komnata Tajemnic?\r\nNowe wydanie różni się od poprzednich nie tylko okładką, ale i wnętrzem – po raz pierwszy na początku każdego tomu pojawi się mapka Hogwartu i okolic, a początki rozdziałów ozdobione będą specjalnymi gwiazdkami.', 'J.K. Rowling', 'upload/1670429437502532903-352x500.jpg', 'Fantastyka'),
	(22, 'Hyperion. Tom 1', 35.26, 47, 624, '2015-12-11', '"Hyperion" to wciągająca i bestsellerowa powieść science-fiction. O odległych galaktykach, końcu Ziemi i niezwykłej misji, jaką wykonać musi siedmioro niezwyciężonych pielgrzymów.\r\n\r\nPowieść, którą pokochały miliony Czytelników na całym świecie z wciągającą niebanalną fabułą, a co najważniejsze wieloma wątkami, zgrabnie łączącymi się w logiczną całość. "Hyperion", czyli książka, którą napisał Dan Simmons przenosi nas w niezwykły świat science-fiction.\r\n\r\nStara i dobrze znana Ziemia umiera, przez co ludzkość zostaje umieszczona na odległych od siebie innych planetach. Nie jest jednak oczywiste, że od teraz wszyscy będą żyć ze sobą w zgodzie. Zbliża się międzygalaktyczna wojna, dlatego też na planetę Hyperion przybywa siedmioro pielgrzymów. Są to Kapłan, Żołnierz, Uczony, Poeta, Kapitan, Detektyw i Konsul. Niezwyciężeni, silni i zdeterminowani, muszą dotrzeć do mitycznych grobowców i znaleźć istotę, która budzi grozę. Możliwe, że tylko ona zna metodę, która mogłaby pomóc zapobiec zagładzie ludzkości. Każdy z przybyłych może przedstawić swoją prośbę, chociaż wysłuchana zostanie wyłącznie jedna. Pozostali będą musieli zginąć.\r\n\r\n"Hyperion" to wciągająca powieść science-fiction. Znany autor pokazuje nam swój kunszt literacki, dzięki któremu trudno nam będzie oderwać się od lektury. Bohaterowie są wyraziście wykreowanymi postaciami, pełnymi sprzeczności i wątpliwości. Nie wahają się jednak przed tym, aby uratować ludzkość od zagłady i sprawić, że możliwy będzie dalszy pokój. Tylko czy będą w stanie wypełnić swoją misję? Czy tajemnicza i przerażająca istota przystanie na ich propozycje i również uzna, że dobro większości jest ważniejsze niż własne?', 'Dan Simmons', 'upload/16704300828609788374805575.jpg', 'Sci-Fi'),
	(23, 'Katedra', 16.43, 13, 104, '2020-11-04', 'Jeśli cenisz sobie polską literaturę science fiction, to opowiadanie "Katedra" jest lekturą obowiązkową! To już klasyka tego gatunku, którą warto przeczytać. Wyrusz w przestrzeń kosmiczną i udaj się na planetoidę skrywającą wiele tajemnic!\r\n\r\nW układzie gwiazdy Lévie doszło do tragicznego wydarzenia. To tam w wyniku wypadku holownik "Sagittarius" musiał znaleźć schronienie na jednej z planetoid. Problemem staje się też zapas tlenu. Okazuje się, że nie wystarczy go dla wszystkich. Izmir Predú decyduje się na akt poświęcenia, tym samym dając załodze szansę na przeżycie.\r\n\r\nJego grób na pozbawionej atmosfery planetoidzie staje się miejscem pielgrzymek. Stało się to po tym, jak właśnie tam uzdrowiony został Kotter Ugerzo - bratanek prezesa korporacji R-L. Wieść o tym cudzie przyczyniła się do uznania tego miejsca za święte. Ale to nie wszystko. Stefan Ugerzo, wuj ozdrowieńca, funduje Katedrę - wielką i majestatyczną budowlę wokół grobu, wyhodowaną z nanozarodników.\r\n\r\nKsiądz Pierre Lavone zostaje wysłany na Izmiriady. Tak na cześć Izmira został nazwany rój planetoid. Kapłan ma za zadanie rozstrzygnąć kwestię cudów oraz świętości tego miejsca. Ma też odkryć tajemnicę Izmiriad. Musi to zrobić, zanim planetoidy wraz z Katedrą przepadną na zawsze w wielkiej pustce międzygwiezdnej.\r\n\r\nJacek Dukaj, autor opowiadania, to uznany pisarz, którego powieści zyskały wielką popularność. Wśród nich są m.in.: "Czarne oceany", "Córka łupieżcy" czy "Imperium chmur".', 'Jacek Dukaj', 'upload/16704301830179788308073209.jpg', 'Sci-Fi'),
	(24, 'Solaris', 27.98, 19, 340, '2022-31-02', 'Najsłynniejsza powieść Stanisława Lema w nowym wydaniu! Dzieło przetłumaczone na kilkadziesiąt języków i dwukrotnie przeniesione na ekran.\r\n\r\nW Solaris Stanisław Lem podejmuje jeden z najpopularniejszych tematów literatury fantastycznej - temat Kontaktu. Z obcą cywilizacją, odmienną formą życia, a może po prostu z Nieznanym, tego Lem jednoznacznie nie dopowiada. Być może dlatego Solaris po kilkudziesiąciu lat od pierwszego wydania wciąż fascynuje.', 'Stanisław Lem', 'upload/16704303143979788308075197.jpg', 'Sci-Fi'),
	(25, 'Anna Karenina', 94.67, 6, 900, '2010-19-06', 'Wspaniała powieść o miłości, wierności, zdradzie, prawie jednostki do szczęścia i cenie, jaką trzeba i wolno za nie zapłacić. Dramat osobisty Anny, która dla namiętnej miłości porzuciła rodzinę, rozwija się równolegle z wątkiem społecznym. Klasyczna konstrukcja, głębia analizy psychologicznej, bogactwo treści ukazują mistrzostwo Lwa Tołstoja - pisarza i myśliciela, jednego z najwybitniejszych przedstawicieli literatury europejskiej XIX wieku.', 'Lew Tołstoj', 'upload/16704305943089788382895179.jpg', 'Romans'),
	(26, 'Krzyżacy', 19.34, 79, 600, '2020-24-02', 'Wydanie Krzyżaków kompletne bez skrótów i cięć w treści. W tym wydaniu znajdziesz odpowiedzi na pytania z podręcznika - „pewniak na teście”, czyli wskazanie zagadnień, które zwykle pojawiają się w pytaniach z danej lektury we wszelkich testach sprawdzających wiedzę, a także w podręcznikach i na klasówkach. Zawiera bardzo szczegółowe streszczenie oraz drugie skrócone, ułatwiające szybkie przygotowanie się przed lekcją. Opracowanie zawiera plan wydarzeń, wnikliwie wyjaśnioną problematykę oraz szerokie charakterystyki bohaterów.\r\n\r\nW tynieckiej gospodzie „Pod Lutym Turem” dwaj rycerze z Bogdańca, Maćko i jego synowiec, młodziutki Zbyszko, spotykają się z dworem księżnej Anny Danuty. Zbyszko od pierwszego wejrzenia zakochuje się w jednej z dwórek księżnej, Danusi. Nie spodziewa się, jak bardzo dziewczyna zostanie skrzywdzona przez Krzyżaków, jeszcze nie wie, że w wielkiej wojnie z Zakonem, która wkrótce się rozegra on, Zbyszko, weźmie udział również z osobistych powodów.', 'Henryk Sienkiewicz', 'upload/167043071395733958401465KS.jpg', 'Powieść_Historyczna'),
	(27, 'Quo vadis', 21.23, 90, 472, '2021-16-07', 'Rzym za czasów cesarza Nerona to miejsce zderzenia dwóch światów - zapatrzonej w siebie, kipiącej od bogactw, pełnej zabaw, uczt i zepsucia rzeczywistości Imperium Rzymskiego oraz rodzącej się kultury chrześcijańskiej, tak odmiennej od wszystkiego, co do tej pory znali ludzie.\r\n\r\nZ pierwszego z owych światów pochodzi Winicjusz, z drugiego Ligia - a jednak tych dwoje tak bardzo odmiennych ludzi połączy miłość silniejsza od wszelkich uczuć, jakich dane im było doświadczyć. Historia ich związku, a także historia szalonego cesarza, pożaru Rzymu i prześladowania wyznawców Chrystusa to tło, na którym rozwija się przed oczami czytelnika moc i potęga religii chrześcijańskiej, rozpoczynającej właśnie swój pochód drogą, na której na zawsze zmieni świat.\r\n\r\nPrzedstawiamy jedną z najbardziej znanych powieści Henryka Sienkiewicza w wydaniu lekturowym, z opracowaniem przygotowanym przez doświadczonych nauczycieli. Czytelnik znajdzie tu dokładnie omówioną problematykę, tło historyczne, charakterystyki bohaterów i szczegółowe streszczenie. Zapraszamy do lektury!', '', 'upload/167043086323834535201465KS.jpg', 'Powieść_Historyczna'),
	(28, 'Westerplatte', 31.11, 45, 460, '2019-02-06', 'Dokładnie o godzinie 5:32 pancernik Schleswig-Holstein rozpoczyna ostrzał polskiego stanowiska wojskowego na Westerplatte, nieopodal Wolnego Miasta Gdańska. Wybucha II wojna światowa - najbardziej krwawy konflikt w historii świata, który całkowicie zmienił jego oblicze.\r\n\r\nTragiczna historia początku wojny i heroiczna obrona Westerplatte wobec przytłaczającej przewagi niemieckiej przeszła już do legendy wojskowości. Poświęcenie polskich żołnierzy i ich ofiarna walka były otuchą dla zaatakowanego narodu. Desperacja i upór zainspirowały Jacka Komudę do stworzenia tej powieści historycznej. Bazując na najnowszych opracowaniach naukowych i najświeższych odkryciach, autor przedstawia dokładnie realia tamtych wstrząsających dni i odtwarza krok po kroku dramatyczne wydarzenia. W ten sposób daje możliwość zrozumienia, dlaczego mała, zupełnie nieprzygotowana Składnica Tranzytowa w Gdańsku wytrzymała aż tydzień wzmożonego naporu sił niemieckich.\r\n\r\nKluczowe znaczenie miały decyzje podjęte przez niezłomnych obrońców stacjonujących wówczas na Westerplatte. Książka Komudy to dokładny raport na temat tego, komu w największym stopniu zawdzięczać można fakt, że Składnica nie poddała się od razu, tylko trwała w uporze do ostatnich chwil. Czytelnik pozna konkretne charaktery. Spojrzy na walczących wówczas żołnierzy jak na zwyczajnych ludzi, którzy w odpowiednim momencie przedłożyli służbę dla Ojczyzny nad własne bezpieczeństwo. Dzięki nim Niemcy odczuli na własnej skórze, co znaczy w praktyce upór Polaków.', 'Jacek Komuda', 'upload/16704309390409788379644469.jpg', 'Powieść_Historyczna'),
	(29, 'Lśnienie', 29.72, 71, 520, '2022-07-08', '"Lśnienie" Stephena Kinga to absolutna klasyka gatunku. Jeden z najlepszych horrorów wszech czasów!\r\n\r\nKariera literacka Jacka Torrance\'a wisi na włosku. Zmagający się z alkoholizmem pisarz dostaje posadę dozorcy w położonym w górach hotelu Panorama. Hotel na zimę staje się miejscem praktycznie odizolowanym od świata. Dlatego potrzebny jest ktoś, kto wówczas dopilnuje tam wszystkiego i przygotuje hotel na przyjęcie gości wraz z wiosną. Jack, jego żona Wendy i pięcioletni synek, Danny, rozpoczynają pustelnicze życie w otoczonej górami i śniegiem Panoramie. Wkrótce jednak obdarzony parapsychicznymi zdolnościami Danny odkrywa, że miejsce to zamieszkują złowieszcze siły, które dla rodziny Torrance\'ów są śmiertelnym zagrożeniem.\r\n\r\nStephen King to pisarz ze wszech miar niezwykły. Powszechnie uznawany za króla horroru, całkowicie zdeklasował jakąkolwiek konkurencję. Zresztą na miano to zapracował sobie nie tylko wyjątkowo wysokim poziomem swych utworów, lecz także niegasnącą od lat, twórczą energią. Już pierwsze powieści, a więc "Carrie" i "Miasteczko Salem" przyniosły mu ogromny sukces. Jednak dopiero "Lśnieniem", które przedstawiamy w tym miejscu, zdeklasował całą literacką konkurencję w kategorii powieści grozy.\r\n\r\nDo legendy kina przeszła już niezapomniana kreacja Jacka Nicholsona w ekranizacji, której podjął się Stanley Kubrick. To dzieło poruszające i głęboko zapadające w pamięć, choć sam Stephen King wyrażał się o nim raczej krytycznie. Zresztą praktycznie żadna ekranizacja jego prozy nie wzbudziła w nim zachwytu. Dlaczego? Co takiego jest w literackim pierwowzorze "Lśnienia"?\r\n\r\nMamy tu rzecz jasna grozę: z początku podskórną, wibrującą gdzieś na drugim planie. Grozę, która z biegiem czasu, z pijackich majaków głównego bohatera zmienia się w namacalną rzeczywistość. King to absolutny mistrz budowania napięcia, ale (co warto podkreślić) odkrywania przed czytelnikiem zawiłej psychiki swoich bohaterów. "Lśnienie" to nie tylko horror, ale również przejmująca opowieść o niszczącej sile uzależnienia i o przezwyciężającej przeszkody sile miłości. Absolutna klasyka gatunku!', 'Stephen King', 'upload/16704310590359788382950090.jpg', 'Horror'),
	(30, 'Miasteczko Salem', 28.99, 54, 528, '2021-07-11', 'Niewielkie miasteczka kojarzą się ze spokojnym, sielskim życiem skupiającym się wokół domowego ogniska. Wydawać by się mogło, że czas płynie tam wolniej, a na ludzi czekają wyłącznie pozytywne chwile. Okazuje się jednak, że to tylko złudzenie.\r\n\r\nGdy Ben Mears wraca do swojej rodzinnej miejscowości, jest przekonany, że odnajdzie tam inspirację potrzebną do ukończenia kolejnej książki. Jego pomysł wymaga zbadania tajemniczego domu na wzgórzu, który skrywa wiele sekretów. Nieoczekiwanie okazuje się, że w Salem zaczynają dziać się rzeczy wzbudzające dreszcz grozy. Giną kolejni ludzie, a policja rozkłada ręce z bezradności. Ben z przerażeniem odkrywa, że mają do czynienia z wampirami, a koszmarna przeszłość ponownie daje o sobie znać.\r\n\r\nCzy mieszkańcom Salem uda się wyjść z tej potyczki zwycięsko? I czy mają jakiekolwiek szanse w tym nierównym starciu z siłami ciemności?', 'Stephen King', 'upload/16704312205209788382343748.jpg', 'Horror'),
	(31, 'Hex', 31.42, 11, 448, '2013-30-05', 'Anglojęzyczny debiut utalentowanego niderlandzkiego autora literatury grozy, zdobywcy Nagrody Hugo nominowanego także do World Fantasy Award.\r\n\r\nKtokolwiek się tu urodził, jest skazany, by zostać tu aż do śmierci. Ktokolwiek się tu osiedli, już nigdy nie opuści tego miejsca.\r\n\r\nMiasteczko Black Spring w malowniczej dolinie rzeki Hudson mogłoby być nie lada atrakcją turystyczną, gdyby nie to, że nocami nawiedza je upiorne widmo. To wiedźma Black Rock, siedemnastowieczne truchło kobiety, której oczy i usta zaszyto. Ślepa i niema wałęsa się po ulicach, wchodzi do wybranych domów. Tam staje przy dziecięcych łóżkach, pogrążona w czuwaniu aż do samego rana. Wszyscy wiedzą, że jeśli wiedźma kiedykolwiek otworzy oczy, konsekwencje będą straszliwe.\r\n\r\nStarszyzna nałożyła na miasto swoistą kwarantannę – korzystają z najnowocześniejszych technik nadzoru, więc nic i nikt nie może wydostać się z Black Spring, a to, że jest nawiedzone, musi pozostać ściśle strzeżoną tajemnicą. Ale młodzi mają już dość przymusowego zamknięcia, sfrustrowani łamią rygorystyczne reguły i ujawniają straszliwą prawdę. Odważny, lecz nieroztropny czyn sprawia, że do łask powracają mroczne praktyki rodem z najgłębszych mroków średniowiecza.\r\n\r\nPrzerażająca opowieść o upiornej klątwie ciążącej nad małym amerykańskim miasteczkiem i jego mieszkańcami.\r\n\r\nEkscytujący nowy głos w gatunku horroru i mrocznego fantasy!', 'Thomas Olde Heuvelt', 'upload/16704313263329788367426220.jpg', 'Horror'),
	(32, 'I że Cię nie opuszczę', 39.69, 34, 488, '2018-04-04', '"I że Cię nie opuszczę" to wciągająca i mroczna powieść o Pakcie, który wydawał się być elitarnym i niepozornym klubem dla małżeństw, a stał się powodem niejednego nieszczęścia.\r\n\r\nDobrze jest dbać o swoje małżeństwo i związek już od samego początku. W końcu w czasach, kiedy rozwodów jest coraz więcej, trudno o prawdziwą i głęboką relację. Co jednak, jeśli nasze starania posuwają się stanowczo za daleko? "I że Cię nie opuszczę" to thriller psychologiczny, który wciąga bez reszty!\r\n\r\nAlice i Jake to młode, kochające się małżeństwo. Nie mają większych problemów, kłótni, nie różnią się w poglądach ani zdaniach. Ona jest prawniczką, ON terapeutką i współwłaścicielem poradni psychologicznej. Mają masę ciekawych planów, wiele lat przed sobą i właśnie postanowili wziąć ślub. Właśnie z tej okazji, od jednego z klientów Alice, otrzymali tajemnicze zaproszenie do elitarnego klubu dla małżeństw o nazwie Pakt. O co w nim chodzi? Początkowo wszystko wyglądało bardzo niewinnie, przejrzyście i jak najbardziej odpowiadało partnerom. Wspieranie par w staraniach o szczęśliwy związek to w końcu dobry cel. Tylko co, jeśli staje się ON nierozerwalny? Za wszelką cenę? Nawet po trupach?\r\n\r\n"I że Cię nie opuszczę" to powieść tajemnicza i niesamowicie wciągająca. Nikt tak naprawdę nie wie, do jakiego stopnia jest w stanie posunąć się w ratowaniu i ochronie swojego małżeństwa. Coś, co z początku wydawało się być ciekawym i urozmaicającym życie pomysłem, stanie się największym przekleństwem. Na dodatek nikt spoza klubu nie może dowiedzieć się o Pakcie. Kara, jaka grozi za rozpowiadanie tajemnic jest niezwykle okrutna. Tylko czy istnieje, jakieś wyjście z tej sytuacji? Co postanowią Alice i Jake? Czy będą w stanie za wszelką cenę walczyć o swoją przyszłość?\r\n\r\nMichelle Richmond jest amerykańską pisarką. Autorka bestsellera "New York Timesa", "Rok we mgle". Zanim zajęła się pisaniem, prowadziła zajęcia z kreatywnego pisania na Uniwersytecie w San Francisco, w California College of the Arts, w St. Mary\'s College of Moraga, oraz na Uniwersytecie Bowling Green State.', 'Michelle Richmond', 'upload/16704314347679788375154597.jpg', 'Kryminał'),
	(33, 'Instytut', 40.12, 89, 672, '2019-09-03', 'Mocny jak To, przerażający jak Podpalaczka!\r\nStephen King powraca do motywów znanych z jego najlepszych książek.\r\n\r\nZjawiają się w nocy.\r\nW ciągu dwóch minut eliminują wszystkie przeszkody.\r\nI uprowadzają obiekt.\r\nInteresują ich dzieci.\r\nWyjątkowe dzieci...\r\n\r\nLuke Ellis budzi się w pokoju do złudzenia przypominającym jego własny, tyle że bez okien. Wkrótce orientuje się, że trafił do tajemniczego Instytutu i nie jest jedynym dzieciakiem, którego tu uwięziono.\r\nTo miejsce odosobnienia dla nastolatków obdarzonych zdolnościami telepatii lub telekinezy. W Instytucie zostaną poddani testom, które wzmocnią ich naturalną, choć nadprzyrodzoną moc.\r\nOpiekunowie nie mają skrupułów - grzeczne dzieci są nagradzane, nieposłuszne - są surowo karane. Wszyscy jednak, prędzej czy później, trafią do drugiej części Instytutu, a stamtąd nikt już nie wraca.\r\n\r\nGdy kolejne dzieci znikają w Tylnej Połowie Luke jest coraz bardziej zdesperowany. Musi uciec i wezwać pomoc. Bo jeśli komuś miałoby się udać, to właśnie jemu.', 'Stephen King', 'upload/16704315660039788381257305.jpg', 'Kryminał'),
	(34, 'Avicii. Biografia Tima Berglinga', 46.78, 12, 384, '2022-05-07', 'Avicii - ten pseudonim jest znany wszystkim, którzy słuchają współczesnej muzyki, i kojarzony z największymi nazwiskami showbiznesu. Szwedzki DJ nazywany był wizjonerem, a jego przedwczesna śmierć zszokowała świat. "Avicii. Biografia Tima Berglinga" Mansa Mosessona to szczegółowa biografia jednego z najzdolniejszych producentów XXI wieku.\r\n\r\nUrodzony w Sztokholmie Tim Berling bardzo wcześnie zaczął zdradzać umiłowanie do muzyki, a przede wszystkim wielki talent w tym zakresie. Był introwertycznym, wyalienowanym nastolatkiem, w którym drzemał talent niemieszczący się w samej Szwecji. Jego kariera zaczęła nabierać tempa w latach dwutysięcznych, kiedy singiel "Seek Bromance" podbił listy przebojów w Szwecji, Belgii i Holandii.\r\n\r\nTim Berling był autorem czterech albumów studyjnych, ale powszechnie było wiadomo, że nadużywa alkoholu. Powodem były ataki paniki, depresja oraz stres związany z występami na żywo. W 2018 cały świat dowiedział się o jego śmierci samobójczej, do której doszło w stolicy Omanu. Po jego odejściu założono fundację "Tim Berling Foundation", która wspiera osoby borykające się z depresją.\r\n\r\n', 'Mans Mosesson', 'upload/16704316434209788324074662.jpg', 'Biografia'),
	(35, 'Ania. Biografia Anny Przybylskiej', 36.86, 5, 392, '2009-09-11', 'Łobuziara z urodą nastolatki i głosem Jana Himilsbacha, w zasadzie nie musiała niczego grać. Pojawiła się w polskim kinie znikąd i od razu stała się fenomenem: przed kamerą bardziej naturalna od szkolonych aktorek, utożsamiała "polski sen lat 90." - była idealną dziewczyną z sąsiedztwa, która trafiła na okładki magazynów i do telewizji w szczytowych godzinach oglądalności. Ania Przybylska została "Królową Serc" w kraju, w którym ludzie sukcesu - zwłaszcza "piękni i młodzi" - nigdy nie mają łatwo.\r\n\r\nByła sympatyczną Marylką ze Złotopolskich, ale też dziewczyną z rozkładówki "Playboya". Raz mówiła, że nie ma pomysłu na życie poza aktorstwem, innym razem - że na pierwszym miejscu jest rodzina. Długo nie miała szczęścia w miłości, lecz ciągle była zakochana.\r\n\r\nSpieszyła się momentami tak, jakby czuła, że to wszystko może zbyt długo nie potrwać. Jakby wiedziała, że szybko musi zawierać związek, zakładać rodzinę, urodzić dzieci, by zdążyć się jeszcze tym wszystkim nacieszyć - opowiadają w książce jej bliscy.\r\n\r\nDługo nie zgadzałam się na tę publikację, wszystko było jeszcze zbyt świeże. Raz jedyny udzieliłam wywiadu, który ukazał się w "Wysokich Obcasach". Po raz pierwszy pomyślałam wtedy, że może warto, by ludzie, którzy kochali moją córkę - a dowody tego uczucia spotykają mnie do dzisiaj - zachowali w pamięci obraz takiej Ani, jaką była naprawdę. Nie ten wykoślawiany w szukających często taniej sensacji mediach, ale prawdziwy. Taki, który mogą znać tylko najbliżsi. I że chciałabym móc taką książkę dać w prezencie wnukom.\r\n\r\nBiografia napisana przez Grzegorza Kubickiego i Macieja Drzewickiego jest właśnie taka - Krystyna Przybylska, matka aktorki', 'Grzegorz Kubicki', 'upload/16704317274949788326840593.jpg', 'Biografia'),
	(36, 'Bogini. Tajemnice życia i śmierci Marilyn Monroe', 48.7, 8, 600, '2022-09-04', 'Chyba każdy choć raz w życiu usłyszał to imię i nazwisko - Marilyn Monroe. Kobieta wielu talentów, aktorka, modelka, piosenkarka i producentka filmowa, która zdobyła swoją popularność w latach 50. i 60. Dzięki niezwykłej biografii autorstwa Anthony\'ego Summersa pod tytułem "Bogini. Tajemnice życia i śmierci Marilyn Monroe" świat tej niezwykłej postaci stanie przed Tobą otworem!\r\n\r\nPodczas pisania biografii "Bogini. Tajemnice życia i śmierci Marilyn Monroe" Anthony Summers skupił się na przedstawieniu jak największej liczby faktów i ciekawostek o znanej i podziwianej sławie. Książka daje odpowiedzi na temat życia prywatnego gwiazdy, jej charakteru, przygód i przeciwności losu, a także tajemniczej śmierci.\r\n\r\nBiografia Marilyn to ponadczasowe dzieło, do którego chętnie sięga się do dziś, ponieważ postać ta stała się ikoną popkultury. Anthony przeprowadził ponad 600 wywiadów, skrupulatnie rozmawiając z przyjaciółmi, kochankami i innymi osobami, które na co dzień towarzyszyły aktorce. Pracę autora docenił Netflix - producent seriali, który postanowił na bazie biografii nakręcić serial pt.: "Marilyn Monroe: Nieznane nagrania".', 'Anthony Summers', 'upload/16704319872319788324086641.jpg', 'Biografia'),
	(37, 'Chłopcy z placu broni', 21.91, 76, 200, '2022-05-12', 'Tytułowy Plac Broni to ulubione miejsce zabaw grupy chłopców, którym przewodzi Janosz Boka. Wśród członków grupy znajduje się również Ernest Nemeczek, główny bohater książki, najniższy stopniem i najmniej poważany chłopiec, który często jest kozłem ofiarnym.\r\n\r\nInna grupa chłopców, Czerwone Koszule, chce zająć Plac Broni, aby móc grać na nim w palanta. Przywódcą tej grupy jest Feri Acz. Walki pomiędzy chłopcami o prawo do Placu Broni, znaczącego dla nich więcej niż zwykły plac dziecięcych zabaw, stanowią oś fabuły powieści.\r\n\r\nGłówny bohater, choć z pozoru jest najsłabszym ogniwem swojej grupy, wykazuje się niezwykłą odwagą i zdobywa szacunek kolegów. Podejmuje szereg heroicznych czynów, w których efekcie zachorował na zapalenie płuc. Mimo choroby bierze udział w decydującej bitwie, ostatkiem sił przyczyniając się do zwycięstwa nad Czerwonymi Koszulami. Jaką cenę przyjdzie Ernestowi Nemeczkowi zapłacić za bohaterskie czyny? Czy Janosz Boka i jego kompani ocalą Plac Broni?\r\n\r\nPowieść w interesujący sposób przedstawia relacje panujące w grupie młodych chłopców oraz próby tworzenia w ich społeczności struktur wojskowych. Dla członków grupy ważne są takie wartości, jak: honor, odwaga, bohaterstwo i braterstwo, jednak wartością nadrzędną zdaje się być dla nich wierność sprawie. Ich postawę przyrównywać można do patriotyzmu.', 'Ferenc Molnar', 'upload/16704321826269788310138088.jpg', 'Powieść_młodzieżowa'),
	(38, 'Dotknij mnie. Dotyk Julii.', 30.54, 34, 444, '2022-31-05', 'Juliette nie dotknęła nikogo od 264 dni.\r\n\r\nNikt nie wie, dlaczego jej dotyk jest zabójczy, ale Przywrócenie ma dla niej plan. Pragną ją wykorzystać jako niebezpieczną broń. Dziewczyna nie zamierza jednak oddać się w ich ręce.\r\n\r\nPo długim czasie w zamknięciu, spragniona wolności, nareszcie odkrywa swoją siłę i po raz pierwszy zaczyna walczyć o nową przyszłość. Znajduje ukojenie w ramionach chłopaka, którego miała stracić na zawsze.\r\n\r\nW tym dystopijnym świecie Tahereh Mafi snuje opowieść o walecznej bohaterce, trudach dorastania i sile miłości. To historia nie do zapomnienia!\r\n\r\nKsiążka zawiera dodatkową nowelkę pt. „Zniszcz mnie”.', 'Tahereh Mafi', 'upload/16704323010739788367461795.jpg', 'Powieść_młodzieżowa'),
	(39, '11 papierowych serc', 24.79, 13, 288, '2022-28-07', 'Rok temu: Życie Elli było idealne. Miała cudownych przyjaciół i niesamowitego chłopaka. Wszystko się zmieniło w momencie wypadku samochodowego. Kiedy Ella obudziła się w szpitalu, nie pamiętała ani tragicznego wydarzenia, ani tygodni przed nim. Nie rozumiała też, dlaczego zerwała ze swoim chłopakiem.\r\n\r\nTeraz: Ella zaczyna otrzymywać papierowe serca od tajemniczego wielbiciela. Ten wie o niej zadziwiająco dużo. Serca zawierają wskazówki mające pomóc dziewczynie przypomnieć sobie życie przed wypadkiem. I zabiorą ją w podróż, której nigdy sobie nie wyobrażała. Podążanie za papierowymi sercami jest najbardziej spontaniczną rzeczą, jaką Ella kiedykolwiek zrobiła… Ale czy znajdzie odpowiedzi na dręczące ją pytania?\r\n\r\n„11 papierowych serc” to książka idealna dla fanów trylogii Do wszystkich chłopców, których kochałam Jenny Han i serii The Kisssing Booth Beth Reekles. Ta urocza, ale też mądra historia wciąga czytelnika i zostaje z nim na długo. Razem z bohaterką wybierz się w podróż śladem papierowych serc i przekonaj, że miłość potrafi przyjść w najbardziej nieoczekiwanym momencie.', 'Kelsey Hartwell', 'upload/16704323689149788367247054.jpg', 'Powieść_młodzieżowa'),
	(40, 'Król Maciuś Pierwszy', 9.89, 21, 276, '2021-25-09', 'Wydanie lektury Król Maciuś Pierwszy kompletne bez skrótów i cięć w treści. W tym wydaniu znajdziesz odpowiedzi na pytania z podręcznika - ?pewniak na teście?, czyli wskazanie zagadnień, które zwykle pojawiają się w pytaniach z danej lektury we wszelkich testach sprawdzających wiedzę, a także w podręcznikach i na klasówkach. Zawiera bardzo szczegółowe streszczenie oraz drugie skrócone, ułatwiające szybkie przygotowanie się przed lekcją. Opracowanie zawiera plan wydarzeń, wnikliwie wyjaśnioną problematykę oraz szerokie charakterystyki bohaterów.\r\n\r\nPewnego dnia mały Maciuś zostaje królem wielkiego kraju. Jest tylko małym chłopcem, ale bardzo się stara rządzić jak najlepiej. Jednak nie wszyscy są mu życzliwi, a on sam też nie zawsze właściwie rozumie to, co się wokół niego dzieje. Bierze udział w wojnie, zaprzyjaźnia się z królem egzotycznego kraju w dalekiej Afryce, reformuje kraj, by był przyjazny dla dzieci, ma wiele ciekawych i niebezpiecznych przygód... Jak skończy się historia króla Maciusia I Reformatora?', 'Janusz Korczak', 'upload/167043245768334166301465KS.jpg', 'Literatura_dziecięca'),
	(41, 'Mały Książe', 7.29, 53, 96, '2021-01-01', 'Wydanie Małego Księcia kompletne bez skrótów i cięć w treści. W tym wydaniu znajdziesz odpowiedzi na pytania z podręcznika - „pewniak na teście”, czyli wskazanie zagadnień, które zwykle pojawiają się w pytaniach z danej lektury we wszelkich testach sprawdzających wiedzę, a także w podręcznikach i na klasówkach. Zawiera bardzo szczegółowe streszczenie oraz drugie skrócone, ułatwiające szybkie przygotowanie się przed lekcją. Opracowanie zawiera plan wydarzeń, wnikliwie wyjaśnioną problematykę oraz szerokie charakterystyki bohaterów.\r\n\r\nMałego Księcia nie trzeba nikomu przedstawiać. Ten chłopiec od lat uczy, jak patrzeć na świat oczami dziecka, jak nie zatracić wrażliwości i wyobraźni, czym jest prawdziwa przyjaźń i miłość.\r\n\r\nPowieść Antoine’a de Saint-Exupéry’ego została przetłumaczona na ponad 270 języków, kochana przez rzesze czytelników, należy do arcydzieł światowej literatury.\r\n\r\nMały Książę to wzruszająca, ciepła, pocieszająca lektura, o której nie sposób zapomnieć. Zapraszamy do lektury, a może kiedyś niespodziewanie i do was przyjdzie mały chłopiec i poprosi: „Proszę, narysuj mi baranka”?', 'Antoine de Saint Exupery', 'upload/16704325847749788375175851.jpg', 'Literatura_dziecięca'),
	(42, 'Tajemniczy ogród', 29.29, 15, 256, '2021-02-02', 'Mary to mała, kapryśna dziewczynka, której życie z dnia na dzień zmienia się całkowicie. Traci rodziców i zostaje przygarnięta przez swego bogatego wuja. Trafia do Misselthwaite Manor - domu pełnego niezwykłych tajemnic. Z czasem dziewczynka zmienia się pod wpływem nowo poznanych ludzi, a jeden z sekretów - tajemniczy ogród od lat zamknięty na klucz - uchyla przed nią rąbka tajemnicy…\r\n\r\n„Tajemniczy Ogród” autorstwa Frances Hodgson Burnett to klasyka światowej literatury. Tym razem dostępna w pięknym, prezentowym wydaniu, idealnym dla wszystkich miłośników tego niezwykłego świata.', 'Frances Hodgson Burnett', 'upload/16704326593789788381549271.jpg', 'Literatura_dziecięca');
/*!40000 ALTER TABLE `ksiazki` ENABLE KEYS */;

-- Zrzut struktury tabela bookstore.opinie
CREATE TABLE IF NOT EXISTS `opinie` (
  `id_opinia` int(11) NOT NULL AUTO_INCREMENT,
  `id_klienta` int(11) NOT NULL,
  `id_oferty` int(11) DEFAULT NULL,
  `opinia` varchar(1000) COLLATE utf8mb4_polish_ci NOT NULL,
  `zdjecie` varchar(1000) COLLATE utf8mb4_polish_ci NOT NULL,
  `link` varchar(1000) COLLATE utf8mb4_polish_ci NOT NULL,
  PRIMARY KEY (`id_opinia`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_polish_ci;

-- Zrzucanie danych dla tabeli bookstore.opinie: ~0 rows (około)
/*!40000 ALTER TABLE `opinie` DISABLE KEYS */;
/*!40000 ALTER TABLE `opinie` ENABLE KEYS */;

-- Zrzut struktury tabela bookstore.users
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `login` varchar(20) COLLATE utf8mb4_polish_ci NOT NULL,
  `haslo` varchar(255) COLLATE utf8mb4_polish_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_polish_ci NOT NULL,
  `czy_zalogowany` int(1) DEFAULT 0,
  `typ` varchar(10) COLLATE utf8mb4_polish_ci DEFAULT NULL,
  `czy_aktywne` int(1) DEFAULT 0,
  `liczba_prob` int(1) DEFAULT 0,
  `blokada` int(1) DEFAULT 0,
  `kod` varchar(50) COLLATE utf8mb4_polish_ci DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `login` (`login`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_polish_ci;

-- Zrzucanie danych dla tabeli bookstore.users: ~0 rows (około)
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`id`, `login`, `haslo`, `email`, `czy_zalogowany`, `typ`, `czy_aktywne`, `liczba_prob`, `blokada`, `kod`) VALUES
	(4, 'admin', '56ef94a5c3b48872cf985090d2d32e3cc94c06196a65ddb9fa1c868c8750fc55', 'admin1@admin', 0, 'admin', 1, 0, 0, 'VoZDXenRV2LbGoSlc59Y');
/*!40000 ALTER TABLE `users` ENABLE KEYS */;

-- Zrzut struktury tabela bookstore.zamowienia
CREATE TABLE IF NOT EXISTS `zamowienia` (
  `id_zamowienia` int(11) NOT NULL AUTO_INCREMENT,
  `imie` varchar(50) COLLATE utf8mb4_polish_ci NOT NULL DEFAULT '0',
  `nazwisko` varchar(50) COLLATE utf8mb4_polish_ci NOT NULL DEFAULT '0',
  `miejscowosc` varchar(50) COLLATE utf8mb4_polish_ci NOT NULL DEFAULT '0',
  `ulica` varchar(50) COLLATE utf8mb4_polish_ci NOT NULL DEFAULT '0',
  `adres` varchar(50) COLLATE utf8mb4_polish_ci NOT NULL DEFAULT '0',
  `telefon` varchar(11) COLLATE utf8mb4_polish_ci NOT NULL DEFAULT '0',
  `metoda` varchar(50) COLLATE utf8mb4_polish_ci NOT NULL DEFAULT '0',
  `id_productu` varchar(11) COLLATE utf8mb4_polish_ci NOT NULL DEFAULT '0',
  `koszt` varchar(11) COLLATE utf8mb4_polish_ci NOT NULL DEFAULT '0',
  `kod_rabatowy` varchar(50) COLLATE utf8mb4_polish_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_zamowienia`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_polish_ci;

-- Zrzucanie danych dla tabeli bookstore.zamowienia: ~0 rows (około)
/*!40000 ALTER TABLE `zamowienia` DISABLE KEYS */;
/*!40000 ALTER TABLE `zamowienia` ENABLE KEYS */;

-- Zrzut struktury wyzwalacz bookstore.wyzwalacz1
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO';
DELIMITER //
CREATE TRIGGER `wyzwalacz1` BEFORE UPDATE ON `users` FOR EACH ROW BEGIN
IF NEW.liczba_prob=3 THEN
SET NEW.liczba_prob=0, NEW.blokada=1;
END IF;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
